AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  A simple backend (read/write to DynamoDB) with a RESTful API endpoint using
  Amazon API Gateway.
Resources:
  HealthUnsuranceAPI:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: dynamodb_crud.lambda_handler
      Runtime: python3.6
      CodeUri: .
      Description: >-
        A simple backend (read/write to DynamoDB) with a RESTful API endpoint
        using Amazon API Gateway.
      MemorySize: 512
      Timeout: 10
      Role: 'arn:aws:iam::065086443563:role/service-role/HealthUnsuranceAPI'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /HealthUnsuranceAPI
            Method: POST
        Api2:
          Type: Api
          Properties:
            Path: /HealthUnsuranceAPI
            Method: GET
        Api3:
          Type: Api
          Properties:
            Path: /HealthUnsuranceAPI
            Method: POST
      Tags:
        'lambda-console:blueprint': microservice-http-endpoint-python3
